name: GNC System  

on:
  push:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - macos-clang
          - linux-gcc
          - windows-msvc

        configuration:
          - Debug
          - Release
        
        block:
          - rasbian
          - ground_station
          - rp2040

        include:
          - toolchain: macos-clang
            os: macos-latest
            compiler: clang
            
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc


    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Configuring "${{ matrix.block }}" Block (${{ matrix.configuration }})
      if: matrix.block == 'rasbian' || matrix.block == 'rp2040'
      run: cmake -S ${{ matrix.block }}/ -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: ${{ matrix.block }} build with ${{ matrix.compiler }}
      if: matrix.block == 'rasbian' || matrix.block == 'rp2040'
      run: cmake --build build

    - name: Test
      if: matrix.block == 'rasbian' || matrix.block == 'rp2040'
      working-directory: build
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest -C -VV --progress ${{ matrix.configuration }}
